"""Add other class in my models file

Revision ID: 3019ad0b8fef
Revises: d88764f48f66
Create Date: 2019-03-04 11:35:25.933176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3019ad0b8fef'
down_revision = 'd88764f48f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subs_email'), 'subs', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subs_email'), table_name='subs')
    op.drop_table('subs')
    # ### end Alembic commands ###
