"""twelnth migration

Revision ID: 4b222b6f9e3b
Revises: 57a364f0a315
Create Date: 2019-02-28 19:47:13.374932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b222b6f9e3b'
down_revision = '57a364f0a315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('dislike', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('like', sa.Integer(), nullable=True))
    op.drop_column('pitches', 'downvote')
    op.drop_column('pitches', 'upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'like')
    op.drop_column('pitches', 'dislike')
    # ### end Alembic commands ###
