"""sixth migration

Revision ID: 97b282343950
Revises: d89657447a27
Create Date: 2019-02-27 11:08:50.586257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b282343950'
down_revision = 'd89657447a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.Integer(), nullable=True))
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
