"""fourth migration

Revision ID: 9eb1cd1269f1
Revises: 1602b3d0503f
Create Date: 2019-02-27 10:42:55.035511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb1cd1269f1'
down_revision = '1602b3d0503f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_title', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'category')
    op.add_column('pitches', sa.Column('pitch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_id')
    op.add_column('comments', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'pitch_title')
    # ### end Alembic commands ###
