"""Isecond migration

Revision ID: d88764f48f66
Revises: 8f6ab1fc1d57
Create Date: 2019-03-01 20:00:46.634264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd88764f48f66'
down_revision = '8f6ab1fc1d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###
